package auth

import (
	"reflect"
	"strings"
	"testing"

	"github.com/arcmantle/nodeman/internal/config"
	keyring "github.com/zalando/go-keyring"
)

type fakeKeychain struct {
	values map[string]string
}

func (f fakeKeychain) Set(service, user, password string) error {
	return nil
}

func (f fakeKeychain) Get(service, user string) (string, error) {
	if value, ok := f.values[user]; ok {
		return value, nil
	}
	return "", keyring.ErrNotFound
}

func (f fakeKeychain) Delete(service, user string) error {
	return nil
}

func TestNormalizeRegistry(t *testing.T) {
	tests := map[string]string{
		"registry.npmjs.org":              "https://registry.npmjs.org/",
		"https://NPM.pkg.github.com":      "https://npm.pkg.github.com/",
		"https://example.com/private/npm": "https://example.com/private/npm/",
	}

	for input, want := range tests {
		got, err := NormalizeRegistry(input)
		if err != nil {
			t.Fatalf("NormalizeRegistry(%q) returned error: %v", input, err)
		}
		if got != want {
			t.Fatalf("NormalizeRegistry(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestBuildUserConfig(t *testing.T) {
	originalBackend := backend
	backend = fakeKeychain{values: map[string]string{
		"https://registry.npmjs.org/":      "token-a",
		"https://npm.pkg.github.com/":      "token-b",
		"https://example.com/private/npm/": "token-c",
	}}
	defer func() {
		backend = originalBackend
	}()

	registries := []config.PackageAuthRegistry{
		{Registry: "https://registry.npmjs.org/", Enabled: true},
		{Registry: "https://npm.pkg.github.com/", Scope: "my-org", Enabled: true},
		{Registry: "https://example.com/private/npm", Enabled: true},
	}

	content, warnings, err := buildUserConfig(registries, []string{"HOME=/tmp"})
	if err != nil {
		t.Fatalf("buildUserConfig returned error: %v", err)
	}
	if len(warnings) != 0 {
		t.Fatalf("buildUserConfig returned warnings: %v", warnings)
	}

	for _, want := range []string{
		"; generated by nodeman",
		"//registry.npmjs.org/:_authToken=token-a",
		"@my-org:registry=https://npm.pkg.github.com/",
		"//npm.pkg.github.com/:_authToken=token-b",
		"//example.com/private/npm/:_authToken=token-c",
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("expected generated config to contain %q, got:\n%s", want, content)
		}
	}
}

func TestSetEnv(t *testing.T) {
	base := []string{"PATH=/bin", "npm_config_userconfig=/old/path", "HOME=/tmp"}
	updated := setEnv(base, "NPM_CONFIG_USERCONFIG", "/new/path")

	want := []string{"PATH=/bin", "NPM_CONFIG_USERCONFIG=/new/path", "HOME=/tmp"}
	if !reflect.DeepEqual(updated, want) {
		t.Fatalf("setEnv() = %#v, want %#v", updated, want)
	}
}

func TestIsPackageManagerCommand(t *testing.T) {
	for _, command := range []string{"npm", "pnpm", "yarn", "corepack"} {
		if !IsPackageManagerCommand(command) {
			t.Fatalf("expected %q to be treated as a package-manager command", command)
		}
	}

	if IsPackageManagerCommand("node") {
		t.Fatal("expected node to not be treated as a package-manager command")
	}
}

func TestHasActiveMappings(t *testing.T) {
	tests := []struct {
		name string
		cfg  *config.Config
		want bool
	}{
		{
			name: "nil config",
			cfg:  nil,
			want: false,
		},
		{
			name: "disabled auth",
			cfg: &config.Config{PackageAuth: config.PackageAuthConfig{
				Enabled:    false,
				Registries: []config.PackageAuthRegistry{{Registry: "https://registry.npmjs.org/", Enabled: true}},
			}},
			want: false,
		},
		{
			name: "enabled with no active registries",
			cfg: &config.Config{PackageAuth: config.PackageAuthConfig{
				Enabled:    true,
				Registries: []config.PackageAuthRegistry{{Registry: "https://registry.npmjs.org/", Enabled: false}},
			}},
			want: false,
		},
		{
			name: "enabled with active registry",
			cfg: &config.Config{PackageAuth: config.PackageAuthConfig{
				Enabled:    true,
				Registries: []config.PackageAuthRegistry{{Registry: "https://registry.npmjs.org/", Enabled: true}},
			}},
			want: true,
		},
	}

	for _, test := range tests {
		if got := HasActiveMappings(test.cfg); got != test.want {
			t.Fatalf("%s: HasActiveMappings() = %t, want %t", test.name, got, test.want)
		}
	}
}

func TestHasStoredToken(t *testing.T) {
	originalBackend := backend
	backend = fakeKeychain{values: map[string]string{
		"https://registry.npmjs.org/": "token-a",
	}}
	defer func() {
		backend = originalBackend
	}()

	present, err := HasStoredToken("registry.npmjs.org")
	if err != nil {
		t.Fatalf("HasStoredToken returned error: %v", err)
	}
	if !present {
		t.Fatal("expected token to be present")
	}

	present, err = HasStoredToken("npm.pkg.github.com")
	if err != nil {
		t.Fatalf("HasStoredToken returned error for missing token: %v", err)
	}
	if present {
		t.Fatal("expected missing token to report false")
	}
}

func TestAuthTokenConfigKey(t *testing.T) {
	got, err := AuthTokenConfigKey("https://example.com/private/npm")
	if err != nil {
		t.Fatalf("AuthTokenConfigKey returned error: %v", err)
	}
	want := "//example.com/private/npm/:_authToken"
	if got != want {
		t.Fatalf("AuthTokenConfigKey() = %q, want %q", got, want)
	}
}
